### ISSUE TITLE
Vite Global/Buffer not defined

### ISSUE THREAD

**Issue by saurra3h** [starc007/web3-wallet-connect#1]
Getting Error Global not defined and Buffer not defined

**Comment by starc007** [comment]
Add these to vite config files
- First install `npm i -D @esbuild-plugins/node-globals-polyfill` & `npm i -D @esbuild-plugins/node-modules-polyfill`
- import `import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill'` & `import { NodeModulesPolyfillPlugin } from '@esbuild-plugins/node-modules-polyfill';`

```jsx
export default config = {
     ..... // config files
     define: {
		global: {}  // for prduction build
      },
    optimizeDeps: {
		disabled: false,
		esbuildOptions: {
			define: {
				global: 'globalThis'
			},
			plugins: [
				NodeGlobalsPolyfillPlugin({
					buffer: true,
					process: true
				}),
				NodeModulesPolyfillPlugin()
			]
		}
	},
      build: {
		commonjsOptions: {
			include: [],        // it will fix require not defined error
		}
	}

}
```

**Comment by starc007** [comment]
- above cofig will fix the errors
